export const booking = [
  {
    id: 1,
    image: require("../assets/images/onb1.png"),
    name: "President Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: false,
    status: "paid",
  },
  {
    id: 2,
    image: require("../assets/images/onb1.png"),
    name: "Marineez Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: true,
    status: "cancelled",
  },
  {
    id: 3,
    image: require("../assets/images/onb1.png"),
    name: "Eco Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: true,
    status: "paid",
  },
  {
    id: 4,
    image: require("../assets/images/onb1.png"),
    name: "Plams Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: true,
    status: "completed",
  },
  {
    id: 5,
    image: require("../assets/images/onb1.png"),
    name: "Bulgari Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: true,
    status: "cancelled",
  },
  {
    id: 6,
    image: require("../assets/images/onb1.png"),
    name: "Palazzo Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: true,
    status: "paid",
  },
  {
    id: 7,
    image: require("../assets/images/onb1.png"),
    name: "Emeralda Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: true,
    status: "paid",
  },
  {
    id: 8,
    image: require("../assets/images/onb1.png"),
    name: "Plams Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    booked: true,
    status: "paid",
  },
];
