export const slides = [
  {
    id: 0,
    backgroundColor: "#051B26",
    image: require("../assets/images/onb1.png"),
    upperstring: "Explore",
    middlestring: "the Unseen",
    lowerstring: "World",
    subtitle: "Discover the world with us",
  },
  {
    id: 1,
    backgroundColor: "#051B26",
    image: require("../assets/images/onb2.png"),
    upperstring: "Travel",
    middlestring: "Comfortably",
    lowerstring: "Easily",
    subtitle: "Travel made easy in your hand",
  },
  {
    id: 2,
    backgroundColor: "#051B26",
    image: require("../assets/images/onb3.png"),
    upperstring: "Best",
    middlestring: "Hotels for",
    lowerstring: "Vacation",
    subtitle: "Enjoy the best vacation with us",
  },
];

export const hotelSlides = [
  {
    id: 1,
    image: require("../assets/images/onb1.png"),
    name: "President Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
  {
    id: 2,
    image: require("../assets/images/onb1.png"),
    name: "Marineez Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
  {
    id: 3,
    image: require("../assets/images/onb1.png"),
    name: "Eco Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
  {
    id: 4,
    image: require("../assets/images/onb1.png"),
    name: "Plams Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
  {
    id: 5,
    image: require("../assets/images/onb1.png"),
    name: "Bulgari Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
  {
    id: 6,
    image: require("../assets/images/onb1.png"),
    name: "Palazzo Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
  {
    id: 7,
    image: require("../assets/images/onb1.png"),
    name: "Emeralda Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
  {
    id: 8,
    image: require("../assets/images/onb1.png"),
    name: "Plams Hotel",
    location: "Paris, France",
    rating: "4.9",
    price: "$30",
    bookmarked: false,
  },
];
